server:
  port: 2500
  host: 'localhost'
  id: 'dev-sealed-email(Smtp)'

bucket:
  endpoint: '192.168.0.144:9000'
  accessKey: 'VBexCBLv7YGQvNew2duP'
  secretKey: '28Mzu6GgvI3bXkjal2hUCOEYG0aNssj8Jv8T0Vbu'
  useSSL: false

session:
  privateKey: 'VEEHKF8dUjUmQqasfirtGR6coar5yfGgfk6C8sQIk1U'
  emailAccessKey: '28Mzu6GgvI3bXkjal2hUCOEYG0aNssj8Jv8T0Vbu'
  cookiePath: '/'
  cookieDomain: 'localhost'
  cookieName: 'NES-DEV'
  cookieSecure: false
  cookieMaxAge: 2592000

auth:
  maxVerifyTimeWindow: 300

domain:
  provided:
      - 'beta.sealed.email'

  DKIMKeySize: 2048 # Will be 4096 in production, just too slow for development
  challengeTemplate: '%s 300 IN TXT "%s"'
  challengePrefix: '_nes-challenge'
  identityTemplate: '_identity.%s 300 IN CNAME _identity.sealed.email'
  spfRecordTemplate: '_spf.%s 300 IN TXT "v=spf1 include:_spf.sealed.email -all"'
  mxRecords:
    - 'doom.mx.sealed.email'
    - 'madlib.mx.sealed.email'
    - 'west.mx.sealed.email'
  dkimTemplate: '%s._domainkey.%s IN TXT "v=DKIM1; k=rsa; p=%s"'
  dmarcTemplate: '_dmarc.{DOMAIN} IN TXT "v=DMARC1; p=none; rua=mailto:dmarc-reports@{DOMAIN}; ruf=mailto:dmarc-failures@{DOMAIN}; sp=none; aspf=r;"'

  service:
    # DNS Resolver Configuration
    retryInterval: 600
    maxRetry: 100

    # How many goroutines to use for DNS resolution
    maxConcurrent: 30

    # To lower the number of Database writes, we will batch the writes
    batchSize: 5
    batchTimeout: 30

    dns: '1.1.1.1:53'
    verifyAll: true

etcd:
    endpoints:
        - 'http://etcd.sealed.email:2379'

    connectionPool:
        refreshInterval: 2 # dev only

    domain:
        username: 'root'
        # This is a development environment, so we're not too worried about security
        # In deployment, only the prefix should be exposed to the services, and
        # the username and password should only be exposed to the relevant services
        # Also we will be using mTLS for the connection anyway
        password: 'root'
        prefix: '/dev/services/domain'
        ttl: 30
        heartbeat: 25
        timeout: 5

    notification:
        username: 'root'
        password: 'root'
        prefix: '/dev/services/notification'
        ttl: 30
        heartbeat: 25
        timeout: 5

    smtp:
        username: 'root'
        password: 'root'
        prefix: '/dev/services/smtp'
        ttl: 30
        heartbeat: 25
        timeout: 5

    api:
        username: 'root'
        password: 'root'
        prefix: '/dev/services/api'
        ttl: 30
        heartbeat: 25
        timeout: 5

certificates:
    # -- For development, we turn off authentication
    requireMTLS: false
    caCert: './dev/.certs/ca/ca.pem'

    domain:
        crt: './dev/.certs/domain/domain.crt'
        key: './dev/.certs/domain/domain.key'

    notification:
        crt: './dev/.certs/notification/notification.crt'
        key: './dev/.certs/notification/notification.key'

    smtp:
        crt: './dev/.certs/smtp/smtp.crt'
        key: './dev/.certs/smtp/smtp.key'

    api:
        crt: './dev/.certs/api/api.crt'
        key: './dev/.certs/api/api.key'

smtp:
  outboundQueue:
    name: 'smtp-output-dev-queue'

    batchSize: 5
    batchTimeout: 30

    maxRetry: 3
    maxConcurrent: 50
    retryInterval: 300

  inboundQueue:
    name: 'smtp-input-dev-queue'

    batchSize: 5
    batchTimeout: 30

    maxRetry: 3
    maxConcurrent: 50
    retryInterval: 300

  certificates:
    crt: './dev/.certs/smtp/tls/smtp.crt'
    key: './dev/.certs/smtp/tls/smtp.key'

  ports:
    tls: 49100 # 465
    plain: 49101 # 25
    startTls: 49102 # 587

  address: 'localhost:%d'
  domain: 'doom.mx.sealed.email'

  portTimeout: 3
  writeTimeout: 100
  readTimeout: 100
  maxMessageBytes: 10000000 # 10MB
  maxRecipients: 100
  maxOutboundRecipients: 50
  allowInsecureAuth: true
  maxLineLength: 2000
  spfHardFail: false

debug:
  forceDialLocalhost: true